# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: Kernel_weight_shape_d
model_type: KernelDModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: gopro-train
    type: PairedImagePetrelDataset
    sdk_gt: s3://Deblur/GoPro/crop/sharp_crops
    sdk_lq: s3://Deblur/GoPro/crop/blur_crops
    meta_info_file: s3://Deblur/GoPro/crop/blur_crops.lmdb/meta_info.txt
    # dataroot_gt: /mnt/lustre/leifei1/data/deblur/train/train/sharp_crops.lmdb
    # dataroot_lq: /mnt/lustre/leifei1/data/deblur/train/train/blur_crops.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImagePetrelTestDataset
    # dataroot_gt: /mnt/lustre/leifei1/data/deblur/test/target.lmdb
    # dataroot_lq: /mnt/lustre/leifei1/data/deblur/test/input.lmdb
    sdk_gt: s3://Deblur/GoPro/GOPRO_Large/test
    sdk_lq: s3://Deblur/GoPro/GOPRO_Large/test
    meta_info_file: s3://Deblur/GoPro/test/input.lmdb/meta_info.txt
    io_backend:
      type: lmdb


network_g:
  type: KernelArch
  dim_embd: 512
  n_head: 8
  n_layers: 9
  codebook_size: 2048
  # same
  latent_size: 361
  emb_dim: 361
  quantizer: 'nearest'
  initialize: false
  
network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64
  n_layers: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  # resume_state: ~


# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]
  
  optim_d:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 800000
    eta_min: !!float 1e-7

  total_iter: 800000
  warmup_iter: -1 # no warm up

  # losses
  reblur_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  
  codebook_opt:
    loss_weight: 10.0
  
  shape_opt:
    type: GaussianLoss
    loss_weight: 1.0
    reduction: mean
  
  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: !!float 1.0 # adaptive_weighting
  

  net_d_iters: 1
  net_d_start_iter: 10001

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
