# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: Kernel_freeze_single_init_ft
model_type: KernelModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: gopro-train
    type: PairedImagePetrelOneDataset
    sdk_gt: s3://Deblur/GoPro/crop/sharp_crops
    sdk_lq: s3://Deblur/GoPro/crop/blur_crops
    meta_info_file: s3://Deblur/GoPro/crop/blur_crops.lmdb/meta_info.txt
    # dataroot_gt: /mnt/lustre/leifei1/data/deblur/train/train/sharp_crops.lmdb
    # dataroot_lq: /mnt/lustre/leifei1/data/deblur/train/train/blur_crops.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImagePetrelOneDataset
    sdk_gt: s3://Deblur/GoPro/crop/sharp_crops
    sdk_lq: s3://Deblur/GoPro/crop/blur_crops
    meta_info_file: s3://Deblur/GoPro/crop/blur_crops.lmdb/meta_info.txt
    # dataroot_gt: /mnt/lustre/leifei1/data/deblur/train/train/sharp_crops.lmdb
    # dataroot_lq: /mnt/lustre/leifei1/data/deblur/train/train/blur_crops.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb


network_g:
  type: KernelArch
  dim_embd: 512
  n_head: 8
  n_layers: 9
  codebook_size: 2048
  fix_modules: ['dcnn']
  # same
  latent_size: 361
  emb_dim: 361
  quantizer: 'nearest'
  initialize: true
  

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  # resume_state: /mnt/lustre/sunjixiang1/code/CodeFormer/experiments/20230912_172854_Kernel_freeze_init_ft/training_states/10000.state
  resume_state: ~
  pretrain_network_dcnn: /mnt/lustre/sunjixiang1/code/CodeFormer/experiments/20230826_113032_Kernel_single/models/net_g_latest.pth
  # resume_state: ~


# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 800000
    eta_min: !!float 1e-7

  total_iter: 800000
  warmup_iter: -1 # no warm up

  # losses
  reblur_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  
  codebook_opt:
    loss_weight: 10.0

# validation settings
val:
  val_freq: !!float 20
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 100
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
