# general settings
name: train_deblurTB-L1Loss
model_type: DeblurTwoBranchModel
num_gpu: auto
manual_seed: 0
syncbn: true # must set to true to avoid bn inplace revision
scale: 1

# dataset and data loader settings
datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: /mnt/lustre/leifei1/data/deblur/train/train/sharp_crops.lmdb
    dataroot_lq: /mnt/lustre/leifei1/data/deblur/train/train/blur_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: /mnt/lustre/leifei1/data/deblur/test/target.lmdb
    dataroot_lq: /mnt/lustre/leifei1/data/deblur/test/input.lmdb
    io_backend:
      type: lmdb


# network structures
network_g:
  type: DeblurTwoBranch
  base_channels: 64
  channel_multipliers: [ 1,2,2,4,4,8 ]
  num_enc_blocks: 2
  use_enc_attention: true
  num_dec_blocks: 2
  use_dec_attention: true
  code_dim: 256
  inpfeat_dim: 32
  align_opt:
    cond_channels: 32
    deformable_groups: 4
  code_selection_mode: Nearest # Predict/Nearest
  quantizer_opt:
    type: L2VectorQuantizer
    num_code: 1024
    code_dim: 256
    spatial_size: [ 16,16 ]

network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64

network_d_local:
  type: NLayerDiscriminator
  input_nc: 3
  ndf: 64
  n_layers: 4

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: experiments/20230613_205403_train_deblurTB/training_states/5000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1600000]
    restart_weights: [1]
    eta_min: !!float 6e-5 # no lr reduce in official vqgan code

  total_iter: 400000

  warmup_iter: -1  # no warm up
  ema_decay: 0.995 # GFPGAN: 0.5**(32 / (10 * 1000) == 0.998; Unleashing: 0.995

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 30001
  manual_seed: 0

# validation settings
# val:
#   val_freq: !!float 5000
#   save_img: False

#   metrics:
#     psnr: # metric name, can be arbitrary
#       type: calculate_psnr
#       crop_border: 0
#       test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  add_image_freq: 600
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True
